name: bse-matrix-run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        basis:
          - sto-3g
          - 6-31++g
        format:
          - json
          - nwchem
        elements:
          - H-Ne
          - C,8,p-17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t download .

      - name: Run Docker container
        run: |
            # Create a directory on the host for the downloaded file
            mkdir -p /tmp/bse_data
            
            # Run the container with the mounted volume
            docker run --rm -v /tmp/bse_data:/data download \
              ${{ matrix.basis }} ${{ matrix.format }} ${{ matrix.elements }}

  manual_dispatch:
   if: github.event_name == 'workflow_dispatch'
   runs-on: ubuntu-latest
   steps:
    - name: Run Docker container from manual dispatch
      run: |
        docker run --rm download \
         ${{ github.event.inputs.basis }} ${{ github.event.inputs.format }} ${{ github.event.inputs.elements }}
